module.exports = [{
  version: "release-0.4",
  label: "v0.4.0",
  sidebar: {
    docs: [
      {type: 'autogenerated', dirName: 'user_docs'},
    ],
    release_notes: [
      {type: 'autogenerated', dirName: 'release_notes'},
    ],
  }
}, {
  version: "release-0.3",
  label: "v0.3.0",
  sidebar: {
    docs: [
      {type: 'autogenerated', dirName: 'user_docs'},
    ],
    release_notes: [
      {type: 'autogenerated', dirName: 'release_notes'},
    ],
  }
}]