module.exports = [
  {
    version: "release-0.6",
    branch: "release-0.6",
    sidebar: {
      docs: [{ type: "autogenerated", dirName: "user_docs" }],
      release_notes: [{ type: "autogenerated", dirName: "release_notes" }],
    },
  },
  {
    version: "release-0.5",
    branch: "release-0.5",
    sidebar: {
      docs: [{ type: "autogenerated", dirName: "user_docs" }],
      release_notes: [{ type: "autogenerated", dirName: "release_notes" }],
    },
  },
];
