module.exports = [
  {
  version: "release-0.4",
  branch: "release-0.4",
  sidebar: {
    docs: [
      {type: 'autogenerated', dirName: 'user_docs'},
    ],
    release_notes: [
      {type: 'autogenerated', dirName: 'release_notes'},
    ],
  }
},
// {
//   version: "release-0.3",
//   branch: "release-0.3",
//   sidebar: {
//     docs: [
//       {type: 'autogenerated', dirName: 'user_docs'},
//     ],
//     release_notes: [
//       {type: 'autogenerated', dirName: 'release_notes'},
//     ],
//   }
// }, 
// {
//   version: "support-docs-rel-0.4",
//   branch: "support/docs-rel-0.4",
//   sidebar: {
//     docs: [
//       {type: 'autogenerated', dirName: 'user_docs'},
//     ],
//     release_notes: [
//       {type: 'autogenerated', dirName: 'release_notes'},
//     ],
//   }
// }
]